import { StyleSheet } from 'react-native';
import { adminColors, adminElevation, adminRadius, adminSpace, adminTypography } from './adminTheme';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: adminColors.background, padding: adminSpace.lg },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: adminSpace.md,
  },
  header: { ...adminTypography.header },
  subheader: { ...adminTypography.subheader, marginTop: adminSpace.xs },
  logoutButton: {
    paddingHorizontal: adminSpace.md,
    paddingVertical: adminSpace.xs,
    backgroundColor: adminColors.primary,
    borderRadius: adminRadius.md,
  },
  logoutText: { ...adminTypography.button, fontSize: 12 },
  sectionNav: { flexDirection: 'row', flexWrap: 'wrap', gap: adminSpace.sm, marginBottom: adminSpace.md },
  sectionNavScrollable: { paddingRight: adminSpace.sm },
  subNav: { marginTop: adminSpace.xs },
  navPill: {
    paddingHorizontal: adminSpace.md,
    paddingVertical: adminSpace.sm + 4,
    minHeight: 44,
    borderRadius: adminRadius.md,
    backgroundColor: adminColors.badgeNeutralBg,
  },
  navPillActive: { backgroundColor: adminColors.primary },
  navPillText: { fontFamily: 'Inter-Medium', color: adminColors.text, fontSize: 12 },
  navPillTextActive: { color: '#FFFFFF' },
  navPillSub: { paddingVertical: adminSpace.xs, paddingHorizontal: adminSpace.sm },
  loading: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  scroll: { flex: 1 },
  card: {
    backgroundColor: adminColors.surface,
    padding: adminSpace.md,
    borderRadius: adminRadius.lg,
    borderWidth: 1,
    borderColor: adminColors.border,
    marginBottom: adminSpace.md,
    ...adminElevation.sm,
  },
  tableCard: {
    backgroundColor: adminColors.surface,
    padding: 0,
    borderRadius: adminRadius.lg,
    borderWidth: 1,
    borderColor: adminColors.border,
    overflow: 'hidden',
    ...adminElevation.sm,
  },
  tableRow: {
    paddingHorizontal: adminSpace.md,
    paddingVertical: adminSpace.sm,
    borderBottomWidth: 1,
    borderBottomColor: adminColors.border,
    minHeight: 44,
    justifyContent: 'center',
  },
  tableRowMuted: { backgroundColor: adminColors.surfaceAlt },
  tableRowLabel: { ...adminTypography.meta, color: adminColors.subtext },
  tableRowValue: { ...adminTypography.body },
  cardActive: { borderColor: adminColors.info, borderWidth: 1.5 },
  title: { fontFamily: 'Inter-SemiBold', color: adminColors.text },
  subtitle: { fontFamily: 'Inter-Regular', color: adminColors.subtext, marginBottom: adminSpace.sm },
  row: { ...adminTypography.body, marginBottom: adminSpace.xs },
  sectionCard: {
    backgroundColor: adminColors.surface,
    padding: adminSpace.md,
    borderRadius: adminRadius.lg,
    borderWidth: 1,
    borderColor: adminColors.border,
    marginBottom: adminSpace.lg,
    ...adminElevation.sm,
  },
  sectionTitle: { fontFamily: 'Inter-SemiBold', color: adminColors.text, fontSize: 15, marginBottom: adminSpace.sm },
  switchRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: adminSpace.sm },
  inputLabel: { ...adminTypography.meta, marginTop: adminSpace.sm },
  input: {
    borderWidth: 1,
    borderColor: adminColors.border,
    borderRadius: adminRadius.md,
    padding: adminSpace.md,
    backgroundColor: adminColors.background,
    fontFamily: 'Inter-Regular',
    color: adminColors.text,
    marginTop: adminSpace.xs,
  },
  buttonRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: adminSpace.md },
  button: {
    flex: 1,
    paddingVertical: adminSpace.md,
    paddingHorizontal: adminSpace.md + adminSpace.xs,
    borderRadius: adminRadius.md,
    alignItems: 'center',
    minHeight: 44,
    justifyContent: 'center',
  },
  buttonPrimary: { backgroundColor: adminColors.accent },
  buttonGhost: { backgroundColor: '#F8FAFC' },
  buttonText: { color: '#FFFFFF', fontFamily: 'Inter-SemiBold' },
  secondaryButtonText: { color: adminColors.accent, fontFamily: 'Inter-SemiBold' },
  outlineButton: {
    marginTop: adminSpace.md,
    borderWidth: 1,
    borderColor: adminColors.primary,
    padding: adminSpace.md,
    borderRadius: adminRadius.md,
    alignItems: 'center',
  },
  outlineButtonText: { color: adminColors.primary, fontFamily: 'Inter-SemiBold' },
  status: { marginTop: adminSpace.sm, color: adminColors.successText, fontFamily: 'Inter-Regular', fontSize: 12 },
  loadingRow: { flexDirection: 'row', alignItems: 'center' },
  warningCard: { borderColor: '#F97316', backgroundColor: adminColors.warningBg },
  warningText: { color: adminColors.warningText },
  helperText: { ...adminTypography.meta, marginTop: adminSpace.xs },
  metaRow: { ...adminTypography.meta },
  cardHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: adminSpace.xs,
  },
  badgeRow: { flexDirection: 'row', gap: adminSpace.xs },
  badge: {
    paddingHorizontal: adminSpace.sm,
    paddingVertical: adminSpace.xs,
    borderRadius: adminRadius.sm,
    backgroundColor: adminColors.badgeNeutralBg,
    borderWidth: 1,
    borderColor: adminColors.border,
  },
  badgeText: { fontFamily: 'Inter-SemiBold', fontSize: 11 },
  badgeNeutral: { backgroundColor: adminColors.badgeNeutralBg, borderColor: adminColors.border },
  badgeNeutralText: { color: adminColors.badgeNeutralText },
  badgeWarning: { backgroundColor: adminColors.badgeWarnBg, borderColor: adminColors.badgeWarnBg },
  badgeWarningText: { color: adminColors.badgeWarnText },
  badgeSuccess: { backgroundColor: adminColors.successBg, borderColor: adminColors.successBg },
  badgeSuccessText: { color: adminColors.successText },
  badgeError: { backgroundColor: adminColors.errorBg, borderColor: adminColors.errorBg },
  badgeErrorText: { color: adminColors.errorText },
  badgeInfo: { backgroundColor: adminColors.badgeInfoBg, borderColor: adminColors.badgeInfoBg },
  badgeInfoText: { color: adminColors.badgeInfoText },
  feeGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: adminSpace.sm, marginTop: adminSpace.sm },
  feeCell: {
    padding: adminSpace.sm,
    backgroundColor: adminColors.background,
    borderRadius: adminRadius.sm,
    minWidth: '45%',
  },
  feeLabel: { fontSize: 12, color: adminColors.subtext, fontFamily: 'Inter-Regular' },
  feeValue: { fontSize: 14, color: adminColors.text, fontFamily: 'Inter-SemiBold' },
  filtersCard: {
    backgroundColor: adminColors.surface,
    padding: adminSpace.md,
    borderRadius: adminRadius.lg,
    borderWidth: 1,
    borderColor: adminColors.border,
    marginBottom: adminSpace.md,
    ...adminElevation.none,
  },
  filterChipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: adminSpace.xs, marginTop: adminSpace.xs, marginBottom: adminSpace.xs },
  filterChip: {
    paddingHorizontal: adminSpace.sm,
    paddingVertical: adminSpace.xs,
    borderRadius: adminRadius.sm,
    backgroundColor: adminColors.badgeNeutralBg,
    borderWidth: 1,
    borderColor: adminColors.border,
  },
  filterChipActive: { backgroundColor: adminColors.primary, borderColor: adminColors.primary },
  filterChipText: { fontFamily: 'Inter-Medium', color: adminColors.text, fontSize: 12 },
  filterChipTextActive: { color: '#FFFFFF' },
  sortRow: { marginTop: adminSpace.sm },
  pageRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: adminSpace.xs },
  pageJump: { flexDirection: 'row', alignItems: 'center', gap: adminSpace.xs },
  pageJumpInput: { width: 60, paddingVertical: adminSpace.xs, paddingHorizontal: adminSpace.sm, marginTop: 0 },
  pageJumpButton: { minWidth: undefined, paddingHorizontal: adminSpace.sm, paddingVertical: adminSpace.xs },
  thumbRow: { flexDirection: 'row', alignItems: 'center', gap: adminSpace.md, marginVertical: adminSpace.sm },
  thumb: { width: 96, height: 60, borderRadius: adminRadius.sm, backgroundColor: '#E5E7EB' },
  linkText: { fontFamily: 'Inter-Medium', color: adminColors.info },
  linkRow: { marginTop: adminSpace.xs },
  banner: {
    padding: adminSpace.md,
    borderRadius: adminRadius.md,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: adminSpace.md,
  },
  bannerText: { fontFamily: 'Inter-Medium', fontSize: 13 },
  bannerLink: { fontFamily: 'Inter-SemiBold', color: adminColors.text },
  bannerSuccess: { backgroundColor: adminColors.successBg },
  bannerSuccessText: { color: adminColors.successText },
  bannerWarning: { backgroundColor: '#FFFBEB' },
  bannerWarningText: { color: '#92400E' },
  bannerError: { backgroundColor: '#FEF2F2' },
  bannerErrorText: { color: adminColors.errorText },
  scrollContent: { paddingBottom: 40 },
  heroCard: {
    backgroundColor: '#0B122A',
    borderRadius: adminRadius.xl,
    padding: adminSpace.lg,
    marginBottom: adminSpace.lg,
    ...adminElevation.lg,
  },
  heroHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: adminSpace.sm + adminSpace.xs,
  },
  heroTitle: { fontFamily: 'Inter-SemiBold', color: '#FFFFFF', fontSize: 16 },
  refreshButton: {
    paddingHorizontal: adminSpace.md,
    paddingVertical: adminSpace.xs,
    borderRadius: adminRadius.md,
    backgroundColor: adminColors.primary,
  },
  refreshText: { color: '#FFFFFF', fontFamily: 'Inter-SemiBold', fontSize: 12 },
  statsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: adminSpace.sm },
  statCard: {
    flexGrow: 1,
    minWidth: '45%',
    backgroundColor: '#11193A',
    borderRadius: adminRadius.md,
    padding: adminSpace.md,
    gap: adminSpace.xs,
  },
  statLabel: { color: '#9CA3AF', fontFamily: 'Inter-Regular', fontSize: 12 },
  statValue: { color: '#FFFFFF', fontFamily: 'Inter-Bold', fontSize: 20, marginTop: adminSpace.xs },
  heroHelper: { color: '#E5E7EB', fontFamily: 'Inter-Regular', fontSize: 11, marginTop: adminSpace.sm },
  skeleton: { backgroundColor: adminColors.surfaceAlt, borderRadius: adminRadius.sm },
  skeletonLine: { height: 10, backgroundColor: adminColors.border, borderRadius: adminRadius.sm },
  stickyBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: adminColors.surface,
    padding: adminSpace.md,
    borderTopWidth: 1,
    borderTopColor: adminColors.border,
    ...adminElevation.md,
  },
});
