import { StyleSheet } from 'react-native';
import { iosColors, iosRadius, iosShadow, iosSpacing, iosTypography } from './iosTheme';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: iosColors.background, padding: iosSpacing.lg },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: iosSpacing.md,
  },
  header: { ...iosTypography.title2 },
  subheader: { ...iosTypography.caption, color: iosColors.secondaryText, marginTop: iosSpacing.xs },
  logoutButton: {
    paddingHorizontal: iosSpacing.md,
    paddingVertical: iosSpacing.xs + 2,
    backgroundColor: iosColors.primary,
    borderRadius: iosRadius.md,
  },
  logoutText: { ...iosTypography.button, color: '#FFFFFF', fontSize: 14 },
  sectionNav: { flexDirection: 'row', flexWrap: 'wrap', gap: iosSpacing.xs, marginBottom: iosSpacing.md },
  sectionNavScrollable: { paddingRight: iosSpacing.sm },
  subNav: { marginTop: iosSpacing.xs },
  navPill: {
    paddingHorizontal: iosSpacing.md,
    paddingVertical: iosSpacing.sm,
    minHeight: 40,
    borderRadius: iosRadius.pill,
    backgroundColor: iosColors.chipBg,
  },
  navPillActive: { backgroundColor: iosColors.primary, borderColor: iosColors.primary, borderWidth: 1 },
  navPillText: { ...iosTypography.subhead, color: iosColors.secondaryText },
  navPillTextActive: { color: '#FFFFFF', fontWeight: '600' },
  navPillSub: { paddingVertical: iosSpacing.xs, paddingHorizontal: iosSpacing.sm },
  loading: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  scroll: { flex: 1 },
  card: {
    backgroundColor: iosColors.surface,
    padding: iosSpacing.md,
    borderRadius: iosRadius.xl,
    borderWidth: 1,
    borderColor: iosColors.separator,
    marginBottom: iosSpacing.md,
    ...iosShadow.card,
  },
  tableCard: {
    backgroundColor: iosColors.surface,
    padding: 0,
    borderRadius: iosRadius.xl,
    borderWidth: 1,
    borderColor: iosColors.separator,
    overflow: 'hidden',
    ...iosShadow.card,
  },
  tableRow: {
    paddingHorizontal: iosSpacing.md,
    paddingVertical: iosSpacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: iosColors.separator,
    minHeight: 44,
    justifyContent: 'center',
  },
  tableRowMuted: { backgroundColor: iosColors.surfaceAlt },
  tableRowLabel: { ...iosTypography.caption, color: iosColors.secondaryText },
  tableRowValue: { ...iosTypography.body },
  cardActive: { borderColor: iosColors.primaryAlt, borderWidth: 1.5 },
  title: { ...iosTypography.headline },
  subtitle: { ...iosTypography.subhead, color: iosColors.secondaryText, marginBottom: iosSpacing.sm },
  row: { ...iosTypography.body, marginBottom: iosSpacing.xs },
  sectionCard: {
    backgroundColor: iosColors.surface,
    padding: iosSpacing.md,
    borderRadius: iosRadius.xl,
    borderWidth: 1,
    borderColor: iosColors.separator,
    marginBottom: iosSpacing.lg,
    ...iosShadow.card,
  },
  sectionTitle: { ...iosTypography.headline },
  switchRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: iosSpacing.sm },
  inputLabel: { ...iosTypography.subhead, color: iosColors.secondaryText, marginTop: iosSpacing.sm },
  input: {
    borderWidth: 1,
    borderColor: iosColors.separator,
    borderRadius: iosRadius.md,
    padding: iosSpacing.md,
    backgroundColor: iosColors.surface,
    ...iosTypography.body,
    color: iosColors.text,
    marginTop: iosSpacing.xs,
  },
  buttonRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: iosSpacing.md, gap: iosSpacing.sm },
  button: {
    flex: 1,
    paddingVertical: iosSpacing.md,
    paddingHorizontal: iosSpacing.lg,
    borderRadius: iosRadius.md,
    alignItems: 'center',
    minHeight: 44,
    justifyContent: 'center',
  },
  buttonPrimary: { backgroundColor: iosColors.primary, ...iosShadow.button },
  buttonGhost: { backgroundColor: iosColors.surfaceAlt },
  buttonText: { ...iosTypography.button, color: '#FFFFFF' },
  secondaryButtonText: { ...iosTypography.button, color: iosColors.primary },
  outlineButton: {
    marginTop: iosSpacing.md,
    borderWidth: 1,
    borderColor: iosColors.primary,
    padding: iosSpacing.md,
    borderRadius: iosRadius.md,
    alignItems: 'center',
  },
  outlineButtonText: { ...iosTypography.button, color: iosColors.primary },
  status: { marginTop: iosSpacing.sm, color: iosColors.success, ...iosTypography.caption },
  loadingRow: { flexDirection: 'row', alignItems: 'center' },
  warningCard: { borderColor: iosColors.warning, backgroundColor: '#FFFBEB' },
  warningText: { color: iosColors.warning },
  helperText: { ...iosTypography.caption, marginTop: iosSpacing.xs, color: iosColors.secondaryText },
  metaRow: { ...iosTypography.caption, color: iosColors.tertiaryText },
  cardHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: iosSpacing.xs,
  },
  badgeRow: { flexDirection: 'row', gap: iosSpacing.xs },
  badge: {
    paddingHorizontal: iosSpacing.sm,
    paddingVertical: iosSpacing.xxs,
    borderRadius: iosRadius.pill,
    backgroundColor: iosColors.chipBg,
    borderWidth: 1,
    borderColor: iosColors.separator,
  },
  badgeText: { ...iosTypography.caption, fontWeight: '600' },
  badgeNeutral: { backgroundColor: iosColors.chipBg, borderColor: iosColors.separator },
  badgeNeutralText: { color: iosColors.chipText },
  badgeWarning: { backgroundColor: iosColors.warningAlt, borderColor: iosColors.warningAlt },
  badgeWarningText: { color: '#FFFFFF' },
  badgeSuccess: { backgroundColor: iosColors.successAlt, borderColor: iosColors.successAlt },
  badgeSuccessText: { color: '#FFFFFF' },
  badgeError: { backgroundColor: iosColors.destructive, borderColor: iosColors.destructive },
  badgeErrorText: { color: '#FFFFFF' },
  badgeInfo: { backgroundColor: iosColors.infoAlt, borderColor: iosColors.infoAlt },
  badgeInfoText: { color: '#FFFFFF' },
  feeGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: iosSpacing.sm, marginTop: iosSpacing.sm },
  feeCell: {
    padding: iosSpacing.sm,
    backgroundColor: iosColors.surfaceAlt,
    borderRadius: iosRadius.md,
    minWidth: '45%',
  },
  feeLabel: { ...iosTypography.caption, color: iosColors.secondaryText },
  feeValue: { ...iosTypography.subhead },
  filtersCard: {
    backgroundColor: iosColors.surface,
    padding: iosSpacing.md,
    borderRadius: iosRadius.xl,
    borderWidth: 1,
    borderColor: iosColors.separator,
    marginBottom: iosSpacing.md,
  },
  filterChipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: iosSpacing.xs, marginTop: iosSpacing.xs, marginBottom: iosSpacing.xs },
  filterChip: {
    paddingHorizontal: iosSpacing.sm,
    paddingVertical: iosSpacing.xs,
    borderRadius: iosRadius.pill,
    backgroundColor: iosColors.chipBg,
    borderWidth: 1,
    borderColor: iosColors.separator,
  },
  filterChipActive: { backgroundColor: iosColors.primary, borderColor: iosColors.primary },
  filterChipText: { ...iosTypography.subhead, color: iosColors.secondaryText },
  filterChipTextActive: { color: '#FFFFFF' },
  sortRow: { marginTop: iosSpacing.sm },
  pageRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: iosSpacing.xs },
  pageJump: { flexDirection: 'row', alignItems: 'center', gap: iosSpacing.xs },
  pageJumpInput: {
    width: 60,
    paddingVertical: iosSpacing.xs,
    paddingHorizontal: iosSpacing.sm,
    marginTop: 0,
    borderWidth: 1,
    borderColor: iosColors.separator,
    borderRadius: iosRadius.md,
  },
  pageJumpButton: { minWidth: undefined, paddingHorizontal: iosSpacing.sm, paddingVertical: iosSpacing.xs },
  thumbRow: { flexDirection: 'row', alignItems: 'center', gap: iosSpacing.md, marginVertical: iosSpacing.sm },
  thumb: { width: 96, height: 60, borderRadius: iosRadius.md, backgroundColor: iosColors.surfaceAlt },
  linkText: { ...iosTypography.subhead, color: iosColors.primary },
  linkRow: { marginTop: iosSpacing.xs },
  banner: {
    padding: iosSpacing.md,
    borderRadius: iosRadius.md,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: iosSpacing.md,
  },
  bannerText: { ...iosTypography.subhead },
  bannerLink: { ...iosTypography.subhead, color: iosColors.primary },
  bannerSuccess: { backgroundColor: iosColors.success, opacity: 0.1 },
  bannerSuccessText: { color: iosColors.success },
  bannerWarning: { backgroundColor: '#FFFBEB' },
  bannerWarningText: { color: iosColors.warning },
  bannerError: { backgroundColor: '#FEF2F2' },
  bannerErrorText: { color: iosColors.destructive },
  scrollContent: { paddingBottom: 40 },
  heroCard: {
    backgroundColor: '#0B122A',
    borderRadius: iosRadius.xl,
    padding: iosSpacing.lg,
    marginBottom: iosSpacing.lg,
    ...iosShadow.card,
  },
  heroHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: iosSpacing.sm,
  },
  heroTitle: { ...iosTypography.title2, color: '#FFFFFF' },
  refreshButton: {
    paddingHorizontal: iosSpacing.md,
    paddingVertical: iosSpacing.xs,
    borderRadius: iosRadius.md,
    backgroundColor: iosColors.primary,
  },
  refreshText: { color: '#FFFFFF', ...iosTypography.caption, fontWeight: '600' },
  statsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: iosSpacing.sm },
  statCard: {
    flexGrow: 1,
    minWidth: '45%',
    backgroundColor: '#11193A',
    borderRadius: iosRadius.md,
    padding: iosSpacing.md,
    gap: iosSpacing.xs,
  },
  statLabel: { color: iosColors.tertiaryText, ...iosTypography.caption },
  statValue: { color: '#FFFFFF', ...iosTypography.title2, marginTop: iosSpacing.xs },
  heroHelper: { color: iosColors.separator, ...iosTypography.caption, marginTop: iosSpacing.sm },
  skeleton: { backgroundColor: iosColors.surfaceAlt, borderRadius: iosRadius.sm },
  skeletonLine: { height: 10, backgroundColor: iosColors.separator, borderRadius: iosRadius.sm },
  stickyBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: iosColors.surface,
    padding: iosSpacing.md,
    borderTopWidth: 1,
    borderTopColor: iosColors.separator,
    ...iosShadow.header,
  },
});
